define_property(GLOBAL PROPERTY CMAKE_FOLDER_STACK )

function(cmake_push_folder folder_name)
get_property(LOCAL_CMAKE_FOLDER_STACK GLOBAL PROPERTY CMAKE_FOLDER_STACK)
list(APPEND LOCAL_CMAKE_FOLDER_STACK ${folder_name})
set_property(GLOBAL PROPERTY CMAKE_FOLDER_STACK ${LOCAL_CMAKE_FOLDER_STACK})
list(JOIN LOCAL_CMAKE_FOLDER_STACK "/" LOCAL_CMAKE_FOLDER_STACK)
set(CMAKE_FOLDER ${LOCAL_CMAKE_FOLDER_STACK} PARENT_SCOPE)

endfunction()

function(cmake_pop_folder)
get_property(LOCAL_CMAKE_FOLDER_STACK GLOBAL PROPERTY CMAKE_FOLDER_STACK)
list(POP_BACK LOCAL_CMAKE_FOLDER_STACK)
set_property(GLOBAL PROPERTY CMAKE_FOLDER_STACK ${LOCAL_CMAKE_FOLDER_STACK})
list(JOIN LOCAL_CMAKE_FOLDER_STACK "/" LOCAL_CMAKE_FOLDER_STACK)
set(CMAKE_FOLDER ${LOCAL_CMAKE_FOLDER_STACK} PARENT_SCOPE)

endfunction()